/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.sql.*;

import java.util.ArrayList;

public class App {

	static Connection connection;
    	
    	public App() {
        	try {
            	connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/coursedb", "root", "rajiniw95");
            	System.out.println("Connected");
        	} catch (Exception e){
            	e.printStackTrace();
            	System.out.println("NOT Connected");
        	}
    	}

    	public static void main(String[] args) {
        	//System.out.println(new App().getGreeting());
        	try {
        		App app = new App();
            		//connection = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/coursedb", "root", "rajiniw95");
            		System.out.println("MAIN");
            		
            		Statement statement = connection.createStatement();
            		ResultSet resultset = statement.executeQuery("select * from courses");

			// print all data in table
            		ArrayList<String> arrayList = new ArrayList<String>(); 
	    		while (resultset.next()) {                      
            			int i = 1;
            			while(i <= 4) {
            				arrayList.add(resultset.getString(i++));
    	     			}
    				System.out.println(resultset.getString("course_code"));
    				System.out.println(resultset.getString("course_name"));
    				System.out.println(resultset.getString("lecturer"));                    
    				System.out.println(resultset.getString("credits"));
			}
		
			// print number of columns
			ResultSetMetaData rsmd = resultset.getMetaData();

            		int column_count = rsmd.getColumnCount();
            
            		Integer column_count_int = new Integer(column_count);
            
            		String column_count_string = column_count_int.toString();
            
            		System.out.println(column_count_string);
		}
		
        	catch (Exception e){
         		e.printStackTrace();
        	}
    	}
    	
    	public String getGreeting() {
        	return "Hello World!";
    	}
    	
}
